FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Controllers/InstitutionController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FoodDeliveryOrderApp.Core.Models;
using FoodDeliveryOrderApp.DAL;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using FoodDeliveryOrderApp.WEB.ViewModels;
using AutoMapper;
using System;
using System.Collections.Generic;

namespace FoodDeliveryOrderApp.WEB.Controllers
{
    public class InstitutionController : Controller
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;

        public InstitutionController(IUnitOfWorkFactory unitOfWorkFactory)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
        }

        // GET: Institution
        [AllowAnonymous]
        public IActionResult Index()
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                return View(unitOfWork.Institutions.GetAll());
            }
        }

        // GET: Institution/Details/5
        [Authorize(Roles = "Admin, User")]
        public IActionResult Details(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var institution = unitOfWork.Institutions.GetById(id.Value);
                if (institution == null)
                {
                    return NotFound();
                }

                return View(institution);
            }
        }

        // GET: Institution/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Institution/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InstitutionType,Name,Image,Description,Id")] Institution institution, IFormFile file)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (ModelState.IsValid)
                {
                    if (file == null)
                    {
                        institution.Image = "default-image.jpg";
                    }
                    else
                    {
                        UploadFile(file, institution);
                    }

                    unitOfWork.Institutions.Add(institution);
                    await unitOfWork.CompleteAsync();

                    return RedirectToAction(nameof(Index));
                }
                return View(institution);
            }
        }

        // GET: Institution/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var institution = unitOfWork.Institutions.GetById(id.Value);
                if (institution == null)
                {
                    return NotFound();
                }
                return View(institution);
            }
        }

        // POST: Institution/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InstitutionType,Name,Image,Description,Id")] Institution institution, IFormFile file)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (id != institution.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        if (file == null)
                        {
                            institution.Image = "default-image.jpg";
                        }
                        else
                        {
                            UploadFile(file, institution);
                        }
                        unitOfWork.Institutions.Update(institution);
                        await unitOfWork.CompleteAsync();
                    }
                    catch (DbUpdateConcurrencyException ex)
                    {
                        throw ex;
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(institution);
            }
        }

        // GET: Institution/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var institution = unitOfWork.Institutions.GetById(id.Value);
                if (institution == null)
                {
                    return NotFound();
                }

                return View(institution);
            }
        }

        // POST: Institution/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var institution = unitOfWork.Institutions.GetById(id);
                unitOfWork.Institutions.Delete(institution);
                await unitOfWork.CompleteAsync();

                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize(Roles = "Admin")]
        public void UploadFile(IFormFile file, Institution institution)
        {
            var fileName = file.FileName;
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                file.CopyTo(fileStream);
            }

            institution.Image = fileName;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult InstitutionOrders(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var institutions = unitOfWork.OrderDetails.GetInstitutionOrdersById(id.Value);

                if (!institutions.Any())
                {
                    return RedirectToAction("EmptyInstitutionOrders");
                }

                var viewModels = institutions.Select(institution => new InstituionOrdersViewModel
                {
                    InstitutionName = institution.ShopCartItem.Dish.Institution.Name,
                    FullName = institution.Order.FullName,
                    DateOrder = institution.Order.DateOrder,
                    DishName = institution.ShopCartItem.Dish.Name,
                    Quantity = institution.ShopCartItem.Quantity,
                    Price = institution.ShopCartItem.Dish.Price,
                    Sum = institution.Price
                });

                return View(viewModels);
            }
        }

        [Authorize(Roles = "Admin, User")]
        public IActionResult EmptyInstitutionOrders()
        {
            return View();
        }
    }
}

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Controllers/ReviewController.cs
using System.Threading.Tasks;
using FoodDeliveryOrderApp.Core.Models;
using FoodDeliveryOrderApp.DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FoodDeliveryOrderApp.WEB.Controllers
{
    public class ReviewController : Controller
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;

        public ReviewController(IUnitOfWorkFactory unitOfWorkFactory)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
        }

        [Authorize(Roles = "User")]
        public IActionResult Create(int institutionId)
        {
            ViewBag.InstitutionId = institutionId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Review review)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.Reviews.Add(review);
                    await unitOfWork.CompleteAsync();

                    return RedirectToAction("Index", "Institution");
                }
                return View(review);
            }
        }
    }
}

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Controllers/ShopCartItemController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using FoodDeliveryOrderApp.Core.Models;
using FoodDeliveryOrderApp.DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FoodDeliveryOrderApp.WEB.Controllers
{
    public class ShopCartItemController : Controller
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly UserManager<User> _userManager;

        public ShopCartItemController(IUnitOfWorkFactory unitOfWorkFactory, UserManager<User> userManager)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
            _userManager = userManager;
        }

        [Authorize(Roles = "User")]
        public IActionResult Index()
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var userId = _userManager.GetUserId(User);
                var shopCartId = unitOfWork.ShopCarts.GetAll()
                    .Where(x => x.UserId == Convert.ToInt32(userId))
                    .Select(com => com.Id).FirstOrDefault();

                ViewBag.ComputeTotalValue = unitOfWork.ShopCartItems.ComputeTotalValue(shopCartId);

                return View(unitOfWork.ShopCartItems.GetShopCartItems(shopCartId));
            }
        }

        [Authorize(Roles = "User")]
        public async Task<RedirectToActionResult> AddToCart(int id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var dish = unitOfWork.Dishes.GetById(id);
                var userId = _userManager.GetUserId(User);
                var shopCartId = unitOfWork.ShopCarts.GetAll().Where(x => x.UserId == Convert.ToInt32(userId)).Select(com => com.Id).FirstOrDefault();

                if (dish != null)
                {
                    unitOfWork.ShopCartItems.AddToCart(dish, 1, shopCartId);
                    await unitOfWork.CompleteAsync();
                }
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "User")]
        public async Task<RedirectToActionResult> RemoveFromCart(int id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var dish = unitOfWork.Dishes.GetById(id);
                var userId = _userManager.GetUserId(User);
                var shopCartId = unitOfWork.ShopCarts.GetAll().Where(x => x.UserId == Convert.ToInt32(userId)).Select(com => com.Id).FirstOrDefault();

                if (dish != null)
                {
                    unitOfWork.ShopCartItems.RemoveLine(dish, shopCartId);
                    await unitOfWork.CompleteAsync();
                }

                return RedirectToAction("Index");
            }
        }
    }
}

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Views/Institution/Create.cshtml
@model FoodDeliveryOrderApp.Core.Models.Institution

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block">
    <h2 class="block-title">Добавление</h2>

    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" asp-controller="Institution" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="InstitutionType" class="control-label"></label>
                    <select asp-for="InstitutionType" asp-items="Html.GetEnumSelectList<FoodDeliveryOrderApp.Core.Enums.InstitutionType>()" class="form-control">
                        <option id="ALL">Выберите тип заведения!</option>
                    </select>
                    <span asp-validation-for="InstitutionType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input type="file" id="file" name="file" asp-for="Image" class="form-control" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="btn-group" role="group">
                        <button type="submit" class="btn btn-success form-submit"><i class="fa fa-save" aria-hidden="true" title="Сохранить" data-toggle="tooltip" data-placement="top"></i> Сохранить</button>
                        <a href="@Url.Action("Index", "Institution")" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true" title="Назад" data-toggle="tooltip" data-placement="top"></i> Назад</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Views/Institution/Delete.cshtml
@model FoodDeliveryOrderApp.Core.Models.Institution

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block">
    <h2 class="block-title">Удаление</h2>

    <h3>Вы действительно хотите удалить эту запись?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.InstitutionType)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.InstitutionType)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Image)
            </dt>
            <dd>
                <img class="img-thumbnail" style="width:15%; height:15%" src="~/images/@Model.Image" />
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <div class="btn-group" role="group">
                    <button type="submit" class="btn btn-success form-submit"><i class="fa fa-save" aria-hidden="true" title="Да" data-toggle="tooltip" data-placement="top"></i> Да</button>
                    <a href="@Url.Action("Index", "Institution")" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true" title="Нет" data-toggle="tooltip" data-placement="top"></i> Нет</a>
                </div>
            </div>
        </form>
    </div>
</div>

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Views/Institution/Details.cshtml
@model FoodDeliveryOrderApp.Core.Models.Institution

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block">
    <h2 clss="block-title">Подробная информация</h2>

    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.InstitutionType)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.InstitutionType)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Image)
            </dt>
            <dd>
                <img class="img-thumbnail" style="width:15%; height:15%" src="~/images/@Model.Image" />
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>
    </div>
    <div>
        <hr />
        <div class="content">
            <h2 clss="block-title">Меню</h2>
            <table class="table table-responsive-sm table-responsive-md table-responsive-lg table-sm">
                <thead>
                    <tr>
                        <th>Блюдо</th>
                        <th>Цена (сом)</th>
                        <th>Описание</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model.Dishes)
                    {
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.Price)</td>
                            <td>@Html.DisplayFor(modelItem => item.Description)</td>
                            @if (User.IsInRole(FoodDeliveryOrderApp.Core.Enums.Roles.User.ToString()))
                            {
                                <td>
                                    <a class="btn btn-warning" href="@Url.Action("AddToCart", "ShopCartItem", new { id = item.Id })"> Добавить в корзину</a>
                                </td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <hr />
    </div>
    @if (User.IsInRole(FoodDeliveryOrderApp.Core.Enums.Roles.Admin.ToString()))
    {
        <div class="form-group">
            <div class="btn-group" role="group">
                <a href="@Url.Action("Edit", "Institution", new { id = Model.Id})" class="btn btn-success"><i class="fas fa-pencil-alt" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                <a href="@Url.Action("Index", "Institution")" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true" title="Назад" data-toggle="tooltip" data-placement="top"></i> Назад</a>
            </div>
        </div>
    }
    @if (User.IsInRole(FoodDeliveryOrderApp.Core.Enums.Roles.User.ToString()))
    {
        <div class="form-group">
            <div class="btn-group" role="group">
                <a href="@Url.Action("Index", "Institution")" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true" title="Назад" data-toggle="tooltip" data-placement="top"></i> Назад</a>
            </div>
        </div>
    }
</div>

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Views/Institution/Edit.cshtml
@model FoodDeliveryOrderApp.Core.Models.Institution

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block">
    <h2 class="block-title">Редактирование</h2>

    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" asp-controller="Institution" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="InstitutionType" class="control-label"></label>
                    <select asp-for="InstitutionType" asp-items="Html.GetEnumSelectList<FoodDeliveryOrderApp.Core.Enums.InstitutionType>()" class="form-control">
                        <option id="ALL">Выберите тип заведения!!</option>
                    </select>
                    <span asp-validation-for="InstitutionType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input type="file" id="file" name="file" asp-for="Image" class="form-control" />
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <div class="btn-group" role="group">
                        <button type="submit" class="btn btn-success form-submit"><i class="fa fa-save" aria-hidden="true" title="Сохранить" data-toggle="tooltip" data-placement="top"></i> Сохранить</button>
                        <a href="@Url.Action("Index", "Institution")" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true" title="Назад" data-toggle="tooltip" data-placement="top"></i> Назад</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Views/Institution/EmptyInstitutionOrders.cshtml
@{
    ViewData["Title"] = "Заказов нет!";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="block-title">Просмотр заказов</h2>
<p>К сожалению у данного заведения нет ни одного заказа!</p>

<a href="@Url.Action("Index", "Institution")" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true" title="Назад" data-toggle="tooltip" data-placement="top"></i> Назад</a>

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Views/Institution/Index.cshtml
@model IEnumerable<FoodDeliveryOrderApp.Core.Models.Institution>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block">
    <h2 class="block-title">Заведения</h2>

    @if (User.IsInRole(FoodDeliveryOrderApp.Core.Enums.Roles.Admin.ToString()))
    {
        <p>
            <a type="button" class="btn btn-primary" href="@Url.Action("Create", "Institution")"> <i class="fa fa-plus"></i> Добавить новую запись</a>
        </p>
    }

    <div class="content">
        <table class="table table-responsive-sm table-responsive-md table-responsive-lg table-sm">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.InstitutionType)</th>
                    <th>@Html.DisplayNameFor(model => model.Name)</th>
                    <th>@Html.DisplayNameFor(model => model.Image)</th>
                    <th>@Html.DisplayNameFor(model => model.Description)</th>
                    <th>Средняя оценка</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.InstitutionType)</td>
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>
                        <td style="width:15%; height:15%">
                            <img class="img-thumbnail" src="~/images/@item.Image" />
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.Description)</td>
                        <td>
                            @if (item.Reviews.Count() != 0)
                            {
                                @foreach (var avgMark in item.Reviews.Average(x => x.Mark).ToString())
                                {
                                    @Html.DisplayFor(modelItem => avgMark)
                                }
                            }
                        </td>
                        <td>
                            @if (User.IsInRole(FoodDeliveryOrderApp.Core.Enums.Roles.Admin.ToString()))
                            {
                                <div class="btn-group float-right" role="group">
                                    <a class="btn btn-success btn-sm" name="editButton" id="editButton" href="@Url.Action("Edit", "Institution", new { id = item.Id })"><i class="fas fa-pencil-alt" aria-hidden="true" title="Редактировать" data-toggle="tooltip" data-placement="top"></i> Редактировать</a>
                                    <a class="btn btn-warning btn-sm" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "Institution", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                                    <a class="btn btn-danger delete-prompt btn-sm" name="deleteButton" id="deleteButton" href="@Url.Action("Delete", "Institution", new {@item.Id })"><i class="fa fa-trash" aria-hidden="true" title="Удалить" data-toggle="tooltip" data-placement="top"></i> Удалить</a>
                                    <a class="btn btn-info btn-sm" name="orderButton" id="orderButton" href="@Url.Action("InstitutionOrders", "Institution", new { id = item.Id })"><i class="fa fa-book" aria-hidden="true" title="Заказы" data-toggle="tooltip" data-placement="top"></i> Заказы</a>
                                </div>
                            }
                            @if (User.IsInRole(FoodDeliveryOrderApp.Core.Enums.Roles.User.ToString()))
                            {
                                <div class="btn-group float-right" role="group">
                                    <a class="btn btn-warning btn-sm" name="detailsButton" id="detailsButton" href="@Url.Action("Details", "Institution", new { id = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Просмотреть" data-toggle="tooltip" data-placement="top"></i> Просмотреть</a>
                                    <a class="btn btn-info btn-sm" name="reviewButton" id="reviewButton" href="@Url.Action("Create", "Review", new { institutionId = item.Id })"><i class="fa fa-eye" aria-hidden="true" title="Оставить отзыв" data-toggle="tooltip" data-placement="top"></i> Оставить отзыв</a>
                                </div>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Views/Institution/InstitutionOrders.cshtml
@using FoodDeliveryOrderApp.WEB.ViewModels
@model IEnumerable<InstituionOrdersViewModel>

@{
    ViewData["Title"] = "Просмотр заказов";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block">
    <h2 class="block-title">Просмотр заказов</h2>

    <div class="content">
        <table class="table table-responsive-sm table-responsive-md table-responsive-lg table-sm">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.InstitutionName)</th>
                    <th>@Html.DisplayNameFor(model => model.FullName)</th>
                    <th>@Html.DisplayNameFor(model => model.DateOrder)</th>
                    <th>@Html.DisplayNameFor(model => model.DishName)</th>
                    <th>@Html.DisplayNameFor(model => model.Quantity)</th>
                    <th>@Html.DisplayNameFor(model => model.Price)</th>
                    <th>@Html.DisplayNameFor(model => model.Sum)</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.InstitutionName)</td>
                        <td>@Html.DisplayFor(modelItem => item.FullName)</td>
                        <td>@Html.DisplayFor(modelItem => item.DateOrder)</td>
                        <td>@Html.DisplayFor(modelItem => item.DishName)</td>
                        <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
                        <td>@Html.DisplayFor(modelItem => item.Price)</td>
                        <td>@Html.DisplayFor(modelItem => item.Sum)</td>
                    </tr>
                }
            </tbody>
        </table>
        <a href="@Url.Action("Index", "Institution")" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true" title="Назад" data-toggle="tooltip" data-placement="top"></i> Назад</a>
    </div>
</div>