FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Controllers/DishController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using FoodDeliveryOrderApp.Core.Models;
using FoodDeliveryOrderApp.DAL;
using FoodDeliveryOrderApp.WEB.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;

namespace FoodDeliveryOrderApp.WEB.Controllers
{
    public class DishController : Controller
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;

        public DishController(IUnitOfWorkFactory unitOfWorkFactory)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
        }

        // GET: Dish
        [AllowAnonymous]
        public IActionResult Index()
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                return View(unitOfWork.Dishes.GetAll());
            }
        }

        // GET: Dish/Details/5
        [Authorize(Roles = "Admin, User")]
        public IActionResult Details(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var dish = unitOfWork.Dishes.GetById(id.Value);
                if (dish == null)
                {
                    return NotFound();
                }

                return View(dish);
            }
        }

        // GET: Dish/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var model = new DishCreateViewModel
                {
                    InstitutionSelectList = new SelectList(unitOfWork.Institutions.GetAll(), "Id", "Name")
                };
                return View(model);
            }
        }

        // POST: Dish/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Price,Description,InstitutionId,Id")] DishCreateViewModel model)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (ModelState.IsValid)
                {
                    var dish = Mapper.Map<Dish>(model);
                    unitOfWork.Dishes.Add(dish);
                    await unitOfWork.CompleteAsync();

                    return RedirectToAction(nameof(Index));
                }
                model.InstitutionSelectList = new SelectList(unitOfWork.Institutions.GetAll(), "Id", "Name", model.InstitutionId);
                return View(model);
            }
        }

        // GET: Dish/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var dish = unitOfWork.Dishes.GetById(id.Value);

                var model = Mapper.Map<DishEditViewModel>(dish);
                model.InstitutionSelectList = new SelectList(unitOfWork.Institutions.GetAll(), "Id", "Name", model.InstitutionId);

                if (dish == null)
                {
                    return NotFound();
                }

                return View(model);
            }
        }

        // POST: Dish/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Name,Price,Description,InstitutionId,Id")] DishEditViewModel model)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (ModelState.IsValid)
                {
                    var dish = Mapper.Map<Dish>(model);

                    unitOfWork.Dishes.Update(dish);
                    await unitOfWork.CompleteAsync();

                    return RedirectToAction(nameof(Index));
                }
                model.InstitutionSelectList = new SelectList(unitOfWork.Institutions.GetAll(), "Id", "Name", model.InstitutionId);
                return View(model);
            }
        }

        // GET: Dish/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var dish = unitOfWork.Dishes.GetById(id.Value);
                if (dish == null)
                {
                    return NotFound();
                }

                return View(dish);
            }
        }

        // POST: Dish/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var dish = unitOfWork.Dishes.GetById(id);
                unitOfWork.Dishes.Delete(dish);
                await unitOfWork.CompleteAsync();

                return RedirectToAction(nameof(Index));
            }
        }
    }
}

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Controllers/InstitutionController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FoodDeliveryOrderApp.Core.Models;
using FoodDeliveryOrderApp.DAL;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using FoodDeliveryOrderApp.WEB.ViewModels;
using AutoMapper;
using System;
using System.Collections.Generic;

namespace FoodDeliveryOrderApp.WEB.Controllers
{
    public class InstitutionController : Controller
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;

        public InstitutionController(IUnitOfWorkFactory unitOfWorkFactory)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
        }

        // GET: Institution
        [AllowAnonymous]
        public IActionResult Index()
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                return View(unitOfWork.Institutions.GetAll());
            }
        }

        // GET: Institution/Details/5
        [Authorize(Roles = "Admin, User")]
        public IActionResult Details(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var institution = unitOfWork.Institutions.GetById(id.Value);
                if (institution == null)
                {
                    return NotFound();
                }

                return View(institution);
            }
        }

        // GET: Institution/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Institution/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InstitutionType,Name,Image,Description,Id")] Institution institution, IFormFile file)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (ModelState.IsValid)
                {
                    if (file == null)
                    {
                        institution.Image = "default-image.jpg";
                    }
                    else
                    {
                        UploadFile(file, institution);
                    }

                    unitOfWork.Institutions.Add(institution);
                    await unitOfWork.CompleteAsync();

                    return RedirectToAction(nameof(Index));
                }
                return View(institution);
            }
        }

        // GET: Institution/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var institution = unitOfWork.Institutions.GetById(id.Value);
                if (institution == null)
                {
                    return NotFound();
                }
                return View(institution);
            }
        }

        // POST: Institution/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InstitutionType,Name,Image,Description,Id")] Institution institution, IFormFile file)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (id != institution.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        if (file == null)
                        {
                            institution.Image = "default-image.jpg";
                        }
                        else
                        {
                            UploadFile(file, institution);
                        }
                        unitOfWork.Institutions.Update(institution);
                        await unitOfWork.CompleteAsync();
                    }
                    catch (DbUpdateConcurrencyException ex)
                    {
                        throw ex;
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(institution);
            }
        }

        // GET: Institution/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var institution = unitOfWork.Institutions.GetById(id.Value);
                if (institution == null)
                {
                    return NotFound();
                }

                return View(institution);
            }
        }

        // POST: Institution/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var institution = unitOfWork.Institutions.GetById(id);
                unitOfWork.Institutions.Delete(institution);
                await unitOfWork.CompleteAsync();

                return RedirectToAction(nameof(Index));
            }
        }

        [Authorize(Roles = "Admin")]
        public void UploadFile(IFormFile file, Institution institution)
        {
            var fileName = file.FileName;
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                file.CopyTo(fileStream);
            }

            institution.Image = fileName;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult InstitutionOrders(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var institutions = unitOfWork.OrderDetails.GetInstitutionOrdersById(id.Value);

                if (!institutions.Any())
                {
                    return RedirectToAction("EmptyInstitutionOrders");
                }

                var viewModels = institutions.Select(institution => new InstituionOrdersViewModel
                {
                    InstitutionName = institution.ShopCartItem.Dish.Institution.Name,
                    FullName = institution.Order.FullName,
                    DateOrder = institution.Order.DateOrder,
                    DishName = institution.ShopCartItem.Dish.Name,
                    Quantity = institution.ShopCartItem.Quantity,
                    Price = institution.ShopCartItem.Dish.Price,
                    Sum = institution.Price
                });

                return View(viewModels);
            }
        }

        [Authorize(Roles = "Admin, User")]
        public IActionResult EmptyInstitutionOrders()
        {
            return View();
        }
    }
}

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Controllers/ShopCartItemController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using FoodDeliveryOrderApp.Core.Models;
using FoodDeliveryOrderApp.DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FoodDeliveryOrderApp.WEB.Controllers
{
    public class ShopCartItemController : Controller
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly UserManager<User> _userManager;

        public ShopCartItemController(IUnitOfWorkFactory unitOfWorkFactory, UserManager<User> userManager)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
            _userManager = userManager;
        }

        [Authorize(Roles = "User")]
        public IActionResult Index()
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var userId = _userManager.GetUserId(User);
                var shopCartId = unitOfWork.ShopCarts.GetAll()
                    .Where(x => x.UserId == Convert.ToInt32(userId))
                    .Select(com => com.Id).FirstOrDefault();

                ViewBag.ComputeTotalValue = unitOfWork.ShopCartItems.ComputeTotalValue(shopCartId);

                return View(unitOfWork.ShopCartItems.GetShopCartItems(shopCartId));
            }
        }

        [Authorize(Roles = "User")]
        public async Task<RedirectToActionResult> AddToCart(int id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var dish = unitOfWork.Dishes.GetById(id);
                var userId = _userManager.GetUserId(User);
                var shopCartId = unitOfWork.ShopCarts.GetAll().Where(x => x.UserId == Convert.ToInt32(userId)).Select(com => com.Id).FirstOrDefault();

                if (dish != null)
                {
                    unitOfWork.ShopCartItems.AddToCart(dish, 1, shopCartId);
                    await unitOfWork.CompleteAsync();
                }
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "User")]
        public async Task<RedirectToActionResult> RemoveFromCart(int id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var dish = unitOfWork.Dishes.GetById(id);
                var userId = _userManager.GetUserId(User);
                var shopCartId = unitOfWork.ShopCarts.GetAll().Where(x => x.UserId == Convert.ToInt32(userId)).Select(com => com.Id).FirstOrDefault();

                if (dish != null)
                {
                    unitOfWork.ShopCartItems.RemoveLine(dish, shopCartId);
                    await unitOfWork.CompleteAsync();
                }

                return RedirectToAction("Index");
            }
        }
    }
}

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodDeliveryOrderApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" asp-append-version="true" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Institution" asp-action="Index" class="navbar-brand">FoodDeliveryOrderApp</a>
            </div>
            <div class="navbar-collapse collapse">
                @if (User.IsInRole(FoodDeliveryOrderApp.Core.Enums.Roles.User.ToString()))
                {
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Institution" asp-action="Index"><i class="fas fa-vihara" aria-hidden="true"></i> Все заведения</a></li>
                        <li><a asp-area="" asp-controller="Dish" asp-action="Index"><i class="fas fa-utensils" aria-hidden="true"></i> Все блюда</a></li>
                        <li><a asp-area="" asp-controller="ShopCartItem" asp-action="Index"><i class="fas fa-shopping-cart" aria-hidden="true"></i> Корзина</a></li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Institution" asp-action="Index">Все заведения</a></li>
                        <li><a asp-area="" asp-controller="Dish" asp-action="Index">Все блюда</a></li>
                    </ul>
                }
                <partial name="_LoginPartial" />

            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - FoodDeliveryOrderApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>