FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Controllers/OrderController.cs
using FoodDeliveryOrderApp.Core.Models;
using FoodDeliveryOrderApp.DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace FoodDeliveryOrderApp.WEB.Controllers
{
    public class OrderController : Controller
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly UserManager<User> _userManager;

        public OrderController(IUnitOfWorkFactory unitOfWorkFactory, UserManager<User> userManager)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
            _userManager = userManager;
        }

        [Authorize(Roles = "User")]
        public IActionResult Checkout()
        {
            return View();
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var userId = _userManager.GetUserId(User);
                var shopCartId = unitOfWork.ShopCarts.GetAll()
                    .Where(x => x.UserId == Convert.ToInt32(userId))
                    .Select(com => com.Id).FirstOrDefault();

                var shopCartItems = unitOfWork.ShopCartItems.GetShopCartItems(shopCartId);

                if (shopCartItems.Count() == 0)
                {
                    ModelState.AddModelError("", "У вас нет ни одного товара в корзине!");
                }

                if (ModelState.IsValid)
                {
                    order = (new Order
                    {
                        FullName = order.FullName,
                        Address = order.Address,
                        Phone = order.Phone,
                        Email = order.Email,
                        DateOrder = DateTime.Now
                    });

                    unitOfWork.Orders.Add(order);
                    await unitOfWork.CompleteAsync();

                    unitOfWork.OrderDetails.CreateOrder(order, shopCartId);
                    unitOfWork.ShopCartItems.HideOrderedItems(shopCartId);
                    await unitOfWork.CompleteAsync();
                    return RedirectToAction("Complete");
                }
            }
            return View(order);
        }

        [Authorize(Roles = "User")]
        public IActionResult Complete()
        {
            return View();
        }
    }
}

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Controllers/ShopCartItemController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using FoodDeliveryOrderApp.Core.Models;
using FoodDeliveryOrderApp.DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FoodDeliveryOrderApp.WEB.Controllers
{
    public class ShopCartItemController : Controller
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly UserManager<User> _userManager;

        public ShopCartItemController(IUnitOfWorkFactory unitOfWorkFactory, UserManager<User> userManager)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
            _userManager = userManager;
        }

        [Authorize(Roles = "User")]
        public IActionResult Index()
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var userId = _userManager.GetUserId(User);
                var shopCartId = unitOfWork.ShopCarts.GetAll()
                    .Where(x => x.UserId == Convert.ToInt32(userId))
                    .Select(com => com.Id).FirstOrDefault();

                ViewBag.ComputeTotalValue = unitOfWork.ShopCartItems.ComputeTotalValue(shopCartId);

                return View(unitOfWork.ShopCartItems.GetShopCartItems(shopCartId));
            }
        }

        [Authorize(Roles = "User")]
        public async Task<RedirectToActionResult> AddToCart(int id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var dish = unitOfWork.Dishes.GetById(id);
                var userId = _userManager.GetUserId(User);
                var shopCartId = unitOfWork.ShopCarts.GetAll().Where(x => x.UserId == Convert.ToInt32(userId)).Select(com => com.Id).FirstOrDefault();

                if (dish != null)
                {
                    unitOfWork.ShopCartItems.AddToCart(dish, 1, shopCartId);
                    await unitOfWork.CompleteAsync();
                }
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "User")]
        public async Task<RedirectToActionResult> RemoveFromCart(int id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var dish = unitOfWork.Dishes.GetById(id);
                var userId = _userManager.GetUserId(User);
                var shopCartId = unitOfWork.ShopCarts.GetAll().Where(x => x.UserId == Convert.ToInt32(userId)).Select(com => com.Id).FirstOrDefault();

                if (dish != null)
                {
                    unitOfWork.ShopCartItems.RemoveLine(dish, shopCartId);
                    await unitOfWork.CompleteAsync();
                }

                return RedirectToAction("Index");
            }
        }
    }
}

FoodDeliveryOrderApp/FoodDeliveryOrderApp.WEB/Views/ShopCartItem/Index.cshtml
@model IEnumerable<FoodDeliveryOrderApp.Core.Models.ShopCartItem>

@{
    ViewData["Title"] = "Корзина";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block">
    <h2 class="block-title">Корзина</h2>

    <div class="content">
        <table class="table table-responsive-sm table-responsive-md table-responsive-lg table-sm">
            <thead>
                <tr>
                    <th>Наименование блюда</th>
                    <th>Количество</th>
                    <th>Цена</th>
                    <th>Итого</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Dish.Name</td>
                        <td>@item.Quantity</td>
                        <td>@item.Dish.Price</td>
                        <td>@(item.Quantity * item.Dish.Price)</td>
                        <td>
                            <a class="btn btn-warning" href="@Url.Action("RemoveFromCart", "ShopCartItem", new { id = item.DishId })"> Удалить</a>
                        </td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td>Итого:</td>
                    <td></td>
                    <td></td>
                    <td>@ViewBag.ComputeTotalValue</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<div class="btn-group float-right" role="group">
    <div class="btn-group float-right" role="group">
        <a class="btn btn-success btn-sm" name="orderButton" id="orderButton" href="@Url.Action("Checkout", "Order")"><i class="fa fa-cart" aria-hidden="true" title="Оплатить" data-toggle="tooltip" data-placement="top"></i> Оплатить</a>
        <a class="btn btn-info btn-sm" name="backButton" id="backButton" href='javascript:history.go(-1)'><i class="fa fa-arrow-left" aria-hidden="true" title="Продолжить покупки" data-toggle="tooltip" data-placement="top"></i> Продолжить покупки</a>
    </div>
</div>